import Head from "next/head";
import Content from "@/components/Content/Content";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://fonts.googleapis.com/css?family=Raleway:300,300i,400,500,500i"
          rel="stylesheet"
        />
      </Head>
      <Content />
    </>
  );
}
